spring.application.name=digital-payment
spring.config.import=optional:classpath:config/rabbitmq.yml
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE}
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT}
spring.datasource.hikari.keepalive-time=${DB_KEEPALIVE_TIME}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW}
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
app.superuser.username=${SUPERUSER_USERNAME}
app.superuser.email=${SUPERUSER_EMAIL}
app.superuser.phone=${SUPERUSER_PHONE}
app.superuser.password=${SUPERUSER_PASSWORD}
app.superuser.first-name=${SUPERUSER_FIRSTNAME}
app.superuser.last-name=${SUPERUSER_LASTNAME}
app.superuser.date-of-birth=${SUPERUSER_DATEOFBIRTH}
app.settlements.batch-size=${SETTLEMENT_BATCH_SIZE}
app.settlements.outbox-batch-size=${SETTLEMENT_OUTBOX_BATCH_SIZE}
app.settlements.enqueue-max-attempts=${SETTLEMENT_MAX_ATTEMPTS}
app.settlements.payment-max-attempts=${SETTLEMENT_PAYMENT_MAX_ATTEMPTS}
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRATION_MS}
sse.expiration.ms=${SSE_EXPIRATION_MS}
transaction.ttl.hours=${TRANSACTION_TTL_HOURS}
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.modulith=${LOGGING_MODULITH}
logging.level.org.springframework.transaction=${LOGGING_TRANSACTIONS}
logging.level.org.hibernate.SQL=${LOGGING_SQL}
logging.level.com.example.digital_payment=${LOGGING_APPLICATION}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
base.provider.url=http://localhost:8080/api/v1/fake-providers/bills
spring.threads.virtual.enabled=true
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
spring.cache.type=${CACHE_PROVIDER}
spring.data.redis.url=${REDIS_URL}
cache.expiration.ms=${CACHE_TTL}
wallet.expiration.ms=${WALLET_CACHE_TTL}
user-details.expiration.ms=${USER_DETALS_CACHE_TTL}
spring.rabbitmq.addresses=${RABBITMQ_URL}
spring.rabbitmq.listener.simple.concurrency=${RABBITMQ_CONCURRENCY}
spring.rabbitmq.listener.simple.max-concurrency=${RABBITMQ_MAX_CONCURRENCY}
spring.rabbitmq.listener.simple.prefetch=${RABBITMQ_PREFETCH}
spring.rabbitmq.listener.simple.acknowledge-mode=${RABBITMQ_ACKNOWLEDGE_MODE}
spring.rabbitmq.listener.simple.default-requeue-rejected=${RABBITMQ_DEFAULT_REQUEUE_REJECTED}
spring.rabbitmq.listener.simple.retry.enabled=${RABBITMQ_RETRY_ENABLED}
spring.rabbitmq.listener.simple.retry.max-retries=${RABBITMQ_MAX_RETRIES}
spring.rabbitmq.listener.simple.retry.initial-interval=${RABBITMQ_INITIAL_INTERVAL_MS}
spring.rabbitmq.listener.simple.retry.multiplier=${RABBITMQ_INTERVAL_MULTIPLIER}
spring.rabbitmq.listener.simple.retry.max-interval=${RABBITMQ_MAX_INTERVAL_MS}
spring.rabbitmq.publisher-confirm-type=${RABBITMQ_PUBLISHER_CONFIRM_TYPE}
spring.rabbitmq.publisher-returns=${RABBITMQ_PUBLISHER_RETURN}
